org: jhubbard
app: reddit-minter-bot
service: reddit-minter-bot
useDotenv: true

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  rateHandler:
    handler: handler.run
    environment:
      APP_ABBR: ${param:APP_ABBR}
      BOT_NAME: ${param:BOT_NAME}
      BOT_USER_AGENT: ${param:BOT_USER_AGENT}
      BOT_PASSWORD: ${param:BOT_PASSWORD}
      REDDIT_CLIENT_ID: ${param:REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${param:REDDIT_CLIENT_SECRET}
      CROSSMINT_CLIENT_SECRET: ${param:CROSSMINT_CLIENT_SECRET}
      CROSSMINT_PROJECT_ID: ${param:CROSSMINT_PROJECT_ID}
      HTCI_USERNAME: ${param:HTCI_USERNAME}
      HTCI_PASSWORD: ${param:HTCI_PASSWORD}
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
